### ISSUE TITLE
Search button doesn't work

### ISSUE THREAD

**Issue by tukanoidd** [huhu/query.rs#10] opened 2024-07-25 09:51 UTC
Hello, tried to use the website, can't get the search functionality to work, getting these errors when trying to press the seatch button
![image](https://github.com/user-attachments/assets/58fd6ebe-9dfc-48fa-b54f-b2769dc2ae78)

I made sure I don't have Adguard and built-in Vivaldi ad blocking enabled for the website, cuz I thought that mb those were blocking some requests on accident, but doesn't look like it.

The 2nd-to-last log is from an extension, happens all the time, can be ignored here.

**Comment by Folyd** [comment] 2024-07-26 09:46
Thanks for the feedback. Could you please give your browser info? I cannot reproduce it in my Vivaldi.
```

Vivaldi | 6.8.3381.48 (Stable channel) (x86_64)
Revision | 79dc6e3dc75f1ca82759568b8aaa16287cbeedb4
OS | macOS Version 14.1.2 (Build 23B92)

```

**Comment by Folyd** [comment] 2024-07-26 12:12
Resolved via commit https://github.com/huhu/query.rs/commit/7b156186b36b64dbfcd745264e50470771efff81

**Closed by Folyd** 2024-07-26 12:12 UTC

**Comment by tukanoidd** [comment] 2024-07-26 12:35
Vivaldi	6.8.3381.46 (Stable channel) stable (64-bit) 
Revision	fc048ddc979dd4b5812491cce07da57059e0bbae
OS	Linux
JavaScript	V8 12.6.228.21
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

While the search bar now shows the entries for me to choose from, the search button itself is still unusable. Enter key works though, so it's not the end of the world

**Comment by Folyd** [comment] 2024-07-26 12:50
You mean this search button? It is un-clickable, this is by design 😅 
![image](https://github.com/user-attachments/assets/92452e9e-5872-429d-9c90-d00b5d698597)

**Comment by tukanoidd** [comment] 2024-07-26 12:50
Ah, fair, my bad then :)
